version: "3.9"
services:
  api:
    build: .
    image: ads-analyzer:latest
    ports: ["8080:8080"]
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - FETCH_TIMEOUT=5s
      - HTTP_FALLBACK=true
      - CACHE_BACKEND=redis
      - CACHE_TTL=10m
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - RATE_PER_SEC=10
      - RATE_BURST=20
      - BATCH_WORKERS=8
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]